# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=50)),
                ('ipo_date', models.DateTimeField(verbose_name='initial public offering')),
                ('value', models.IntegerField(default=10)),
                ('stock_code', models.CharField(max_length=4)),
            ],
        ),
    ]
